version: 1.6.6.{build}
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore Razor.sln
build:
  project: Razor.sln
  verbosity: minimal
test: off
after_build:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    python --version
    
    python.exe -m pip install --upgrade pip
    
    pip install mkdocs
    
    pip install mkdocs-material
    
    pip install mkdocs-git-revision-date-plugin
    
    cd help
    
    mkdocs build
artifacts:
- path: bin\Win32\Release
  name: Razor-dev-preview
- path: help\site
  name: Razor-site
deploy:
- provider: GitHub
  release: Razor-dev-preview
  description: Auto-build by AppVeyor\n\nThis is built automatically after each commit to master, so it may contain bugs and/or unfinished features but is generally considered stable. Use at your own risk.\n\nOfficial releases will be listed here and given proper version numbers with release notes.
  auth_token:
    secure: 8F11pQiKmjN7rkwx4TfXay3Z3Ocj+5zpKGeXWYuK/LLGY8HCtFYoXzmGzlePwDwX
  prerelease: true
  force_update: true
skip_commits:
  message: /\[chore\]/
  files:    
    - help/
    - docs/
    - '**/*.md'
    - '**/*.ps1'
    - '**/*.yml'
