site_name: Razor - Ultima Online Assistant
site_description: Razor is a free tool designed to help with simple tasks while playing Ultima Online
site_author: Project maintained by Mark Wagner (Quick)
site_url: http://www.uor-razor.com
copyright: Copyright 2020 - Mark Wagner (Quick)
google_analytics: ['UA-20537997-5', 'uor-razor.com']
repo_url: https://github.com/markdwags/Razor
repo_name: Razor
edit_uri: "tree/master/help/docs"
nav:
- Home: index.md
- Download: download.md
- Install:
    - Windows: install/windows.md
    - Linux: install/linux.md
- Release Notes: releasenotes.md
- Help Guide:
    - Help Overview: help/index.md
    - General: help/general.md
    - Options: help/options.md    
    - Display/Counters: help/displaycounters.md
    - Arm/Dress: help/armdress.md
    - Skills: help/skills.md
    - Agents: help/agents.md
    - Filters: help/filters.md
    - Hot Keys: help/hotkeys.md
    - Macros: help/macros.md
    - Scripts: help/scripts.md
    - Friends: help/friends.md    
    - Screen Shots: help/screenshots.md
    - Advanced: help/advanced.md
- Scripting Guide:
    - Scripting Overview: guide/index.md
    - Commands: guide/commands.md
    - Comments: guide/comments.md
    - Condition Loops: guide/conditionloops.md
    - Expressions: guide/expressions.md
    - Keywords: guide/keywords.md
    - Layers: guide/layers.md
    - Variables: guide/variables.md
- UOAssist API: uoaapi.md

theme: 
    name: material    
    language: en    
    favicon: images/razor.ico
    icon:
        repo: fontawesome/brands/github
    palette:
        primary: red
        accent: blue
        scheme: slate
    font:
        text: Mulish
        code: Fira Code
    logo: images/razor.png

markdown_extensions:
  - admonition
  - toc:
        baselevel: 3    
        permalink: true    
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search  
  - git-revision-date
